services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -c \"SELECT ST_Transform(ST_SetSRID(ST_Point(0,0),4326),2056)\" > /dev/null 2>&1"]
      interval: 3s
      timeout: 10s
      retries: 30
